{% set name = "pegasus-wms.worker" %}
{% set version = "5.0.2" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52473e2c02cf350e71f3f930d6d4a69d0eca53da7d6071358732326f4f256e37
  patches:
    # https://github.com/pegasus-isi/pegasus/pull/27
    - 0001-pegasus-worker-use-implicit-namespace-packages.patch
    # loosen globus-sdk requirement
    - requirements.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
    - setuptools
  run:
    - boto3 >1.12,<1.18
    - globus-sdk >=1.4.1,<2.0.0a0
    - python >=3.5
    - six >=1.9.0

test:
  requires:
    - pip
  imports:
    - Pegasus.tools.worker_utils
  commands:
    # check requirements
    - python -m pip check
    # check cli
    - python -m Pegasus.cli.pegasus-globus-online-init --help
    - python -m Pegasus.cli.pegasus-globus-online --help
    - python -m Pegasus.cli.pegasus-integrity --help
    - python -m Pegasus.cli.pegasus-transfer --help

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
