{% set name = "pegasus-wms.worker" %}
{% set version = "5.0.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e84ba28280f7955099efb8a3556a9758a2581b432c13396a6b9b15c5ac51baf2
  patches:
    # https://github.com/pegasus-isi/pegasus/pull/27
    - 0001-pegasus-worker-use-implicit-namespace-packages.patch
    # loosen globus-sdk requirement
    - requirements.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - boto3
    - globus-sdk >=1.4.1,<2.0.0a0
    - python
    - six >=1.9.1

test:
  requires:
    - pip
  imports:
    - Pegasus.tools.worker_utils
  commands:
    - pip check
    - python -m Pegasus.cli.pegasus-globus-online-init --help
    - python -m Pegasus.cli.pegasus-globus-online --help
    - python -m Pegasus.cli.pegasus-integrity --help
    - python -m Pegasus.cli.pegasus-transfer --help

about:
  home: https://pegasus.isi.edu
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
