{% set name = "pegasus-wms.worker" %}
{% set version = "5.0.8" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 90b25bdd9793f39ff5d2d50e58c611bf848c58dd32be9808c5d14e8883148cff
  patches:
    # https://github.com/pegasus-isi/pegasus/pull/27
    - 0001-pegasus-worker-use-implicit-namespace-packages.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools <69
    - wheel
  run:
    - boto3 >1.12
    - globus-sdk >=3.23.0
    - python >=3.6
    - six >=1.9.0

test:
  requires:
    - pip
  imports:
    - Pegasus.tools.worker_utils
  commands:
    # check requirements
    - python -m pip check
    # check cli
    - python -m Pegasus.cli.pegasus-globus-online-init --help
    - python -m Pegasus.cli.pegasus-globus-online --help
    - python -m Pegasus.cli.pegasus-integrity --help
    - python -m Pegasus.cli.pegasus-transfer --help

about:
  home: https://pegasus.isi.edu
  dev_url: https://github.com/pegasus-isi/pegasus.git
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pegasus Workflow Management System Python API

extra:
  recipe-maintainers:
    - duncanmmacleod
